cc_test(
    name = "test_spot_micro_kinematics",
    size = "small",
    srcs = ["test_spot_micro_kinematics.cc", "test_spot_micro_leg.cc", "test_utils.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//spot_micro/spot_micro_kinematics/src:spot_micro_kinematics",
        "@com_google_googletest//:gtest_main",
    ],
)
