package(default_visibility = ["@//visibility:public"])

cc_test(
    name = "smoke_test_test",
    size = "small",
    srcs = ["smoke_test_test.cc"],
    deps = [
        "@//spot_micro/cpp/apps/smoke_test/src:smoke_test_library",
        "@com_google_googletest//:gtest_main",
    ],
)
