cc_test(
    name = "smoke_test_test",
    size = "small",
    srcs = ["smoke_test_test.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp/apps/smoke_test/src:smoke_test_library",
        "@com_google_googletest//:gtest_main",
    ],
)
