---
name: Functional Test
on:
  push:
    branches: ["main"]
jobs:
  functional-test:
    name: Functional Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install behave
        run: pip install behave
      - name: pwd
        run: pwd
      - name: Bazel Test
        run: make bazel/test
